# Config file for Superman 64 US Recompilation.
[input]
entrypoint = 0x80000400
# Paths are relative to the location of this config file.
# elf_path = "superman.us.elf"
symbols_file_path = "Superman64RecompSyms/superman.us.syms.toml"
rom_file_path = "baserom.us.z64"
output_func_path = "RecompiledFuncs"
use_absolute_symbols = false

[patches]
stubs = [
]

ignored = [
]

# fixes a bug with the recompiler handling an Indirect tail call.
# [[patches.instruction]]
# func = "func_80040C54"
# vram = 0x80040C8C
# value = 0x03E00008 # jr $s3 -> jr $ra

# Disable SP_STATUS_REG access (memory mapped registers not supported).
# [[patches.instruction]]
# func = "_uvScDlistRecover"
# vram = 0x8022B678
# value = 0x00000000 # sw $t6, 0x10($t7) -> nop
# 
# Disable MFC0 register access (register index not supported).
# [[patches.instruction]]
# func = "func_80231A10"
# vram = 0x80231A10
# value = 0x00000000 # mfc0 $v0, $9 -> nop
# 
# Disable MTC0 register access (register index not supported).
# [[patches.instruction]]
# func = "func_80231A10"
# vram = 0x80231A18
# value = 0x00000000 # mtc0 $v0, $9 -> nop

