# Config file for Superman 64 US Recompilation.
[input]
entrypoint = 0x80000400
# Paths are relative to the location of this config file.
# elf_path = "superman.us.elf"
symbols_file_path = "Superman64RecompSyms/superman.us.syms.toml"
rom_file_path = "baserom.us.z64"
output_func_path = "RecompiledFuncs"
use_absolute_symbols = false

[patches]
stubs = [
]

ignored = [
]

[[patches.hook]]
func = "func_80004918"
text = "load_overlays(ctx->r4, ctx->r5, SUB32(ctx->r10, ctx->r9));"
before_vram = 0x80004A40

[[patches.hook]]
func = "func_8001A604"
text = "load_overlays(ctx->r4, ctx->r5, SUB32(ctx->r11, ctx->r10));"
before_vram = 0x8001A8E4

